// Generated by dts-bundle v0.7.2

export function ValidationTrigger<T extends ReceiveValidity>(): any;
export function Validate<T extends ReceiveValidity>(validators: IMVValidators<T>, validateWith?: Array<string>): any;

/**
    * @description Тип для описания валидности полей класса T.
    */
export interface MVValidity {
        [key: string]: IMVFieldValidity;
}
/**
    * @description Интерфейс для описания набора валидностей поля
    */
export interface IMVFieldValidity {
        [key: string]: boolean;
}
/**
    * @description Тип функции-валидатора
    */
export type MVValidator<T> = (value: T, context: any) => boolean;
/**
    * @description Набор валидаторов поля для key-критериев
    */
export interface IMVValidators<T> {
        [key: string]: MVValidator<T>;
}
/**
    * @description Интерфейс, который по хорошему должен реализовать класс, принимающий ошибки
    */
export interface ReceiveValidity {
        receiveErrors(validity: MVValidity): void;
}

